=== redhat-developer/developers.redhat.com/_developer-materials/developer_materials.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="developerMaterials">
		<xs:annotation>
			<xs:documentation> 
				Each XML file will be used by awestruct for loading developer
				materials for each product. It is suggested the name of each file be the lowercase
				hyphenated name of the project category (e.g. development-tools.xml or
				business-rules.xml). The file can list materials as well as locations to
				scan.
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:element type="itemType" name="item"/>
				<xs:element type="scanType" name="scan"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="itemType">
		<xs:annotation>
			<xs:documentation>Each item not scanned for must be listed.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element type="xs:string" name="summary">
				<xs:annotation>
					<xs:documentation>A one or two sentence summary of the item.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="contributorsType" name="contributors" minOccurs="0"/>
			<xs:element type="technologiesType" name="technologies"/>
			<xs:element type="prerequisitesType" name="prerequisites" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="name" use="required" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					A short name for the material, typically no more than 40-50 characters.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="author" use="required" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					The github id (preferred), email address or name of the author of the item.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="level">
			<xs:annotation>
				<xs:documentation>The difficulty of the item.</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="Beginner">
						<xs:annotation>
							<xs:documentation>Material aimed at beginners.</xs:documentation>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="Intermediate">
						<xs:annotation>
							<xs:documentation>Material aimed at intermediate users.</xs:documentation>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="Advanced">
						<xs:annotation>
							<xs:documentation>Material aimed at advanced users.</xs:documentation>
						</xs:annotation>
					</xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="type" use="required">
			<xs:annotation>
				<xs:documentation>The type of the item.</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="Quickstart">
						<xs:annotation>
							<xs:documentation>
								A quickstart, a simple example showing a single use case or API.
							</xs:documentation>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="BOM">
						<xs:annotation>
							<xs:documentation>A Maven Bill of Materials.</xs:documentation>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="Showcase">
						<xs:annotation>
							<xs:documentation>
								A showcase example, a complete application.
							</xs:documentation>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="Screencast">
						<xs:annotation>
							<xs:documentation>
								A screencast showing how to achieve a task.
							</xs:documentation>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="Webinar">
						<xs:annotation>
							<xs:documentation>A webinar.</xs:documentation>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="Video">
						<xs:annotation>
							<xs:documentation>A video.</xs:documentation>
						</xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="Guide">
						<xs:annotation>
							<xs:documentation>A guide.</xs:documentation>
						</xs:annotation>
					</xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="contributorsType">
		<xs:annotation>
			<xs:documentation>Any additional contributors to the item.</xs:documentation>
		</xs:annotation>
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element type="xs:string" name="contributor">
				<xs:annotation>
					<xs:documentation>
						The github id (preferred), email address or name of the contributor to the item. 
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="technologiesType">
		<xs:annotation>
			<xs:documentation>
				A list of technoligies demonstrated by the material, will be used as keywords for searches.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element type="xs:string" name="keyword">
				<xs:annotation>
					<xs:documentation>
						A technology demonstrated by the material, e.g. EJB, JSF,
						JBoss AS etc. The list of keywords is open.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="prerequisitesType">
		<xs:annotation>
			<xs:documentation>Items that should be viewed before this one.</xs:documentation>
		</xs:annotation>
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element type="xs:string" name="prerequisite">
				<xs:annotation>
					<xs:documentation>The name of another item that should be viewed before this one.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="scanType">
		<xs:annotation>
			<xs:documentation>
				The metadata for much of the developer materials is discovered by
				scanning directory structures. Supported formats include Markdown with front matter,
				Markdown with inline tags (as described at ...), Asciidoc with frontmatter and
				Asciidoc with Asciidoc metadata. 
			</xs:documentation>
		</xs:annotation>
		<xs:attribute name="git-url" type="xs:anyURI">
			<xs:annotation>
				<xs:documentation>The URL of a git repository to clone and scan.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== redhat-developer/developers.redhat.com/_developer-materials/_example-product.xml
<?xml version="1.0" encoding="UTF-8"?>
<developerMaterials xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="urn:jboss-developer:developer-materials"
    xsi:schemaLocation="urn:jboss-developer:developer-materials developer_materials.xsd">

    <item name="Helloworld Quickstart" author="Pete Muir" type="Quickstart">
        <summary>The most basic quickstart</summary>
        <contributors>
            <contributor>Burr Sutter</contributor>
            <contributor>Rafael Benevides</contributor>
            <contributor>Sande Gilda</contributor>
        </contributors>
        <technologies>
            <keyword>Serlvet</keyword>
            <keyword>Java EE</keyword>
        </technologies>
    </item>

    <item name="Java EE BOM" author="PShelly McGowan" type="BOM">
        <summary>The BOM for all Java EE APIs</summary>
        <contributors>
            <contributor>Paul Gier</contributor>
        </contributors>
        <technologies>
            <keyword>Java EE</keyword>
        </technologies>
    </item>

    <scan git-url="https://github.com/jboss-jdf/jboss-as-quickstart.git"/>

</developerMaterials>
